/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arrays;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.Integer.sum;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class Main extends javax.swing.JFrame {

    ArrayList<Worker> workers = new ArrayList<Worker>();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel_exercise14Part1 = new javax.swing.JPanel();
        jLabel_exercise14Part1 = new javax.swing.JLabel();
        jLabel2_result = new javax.swing.JLabel();
        jLabel3_outputA = new javax.swing.JLabel();
        jButton1_calculate = new javax.swing.JButton();
        jLabel4_outputB = new javax.swing.JLabel();
        jPanel__exercise39Part1 = new javax.swing.JPanel();
        jButton2_calculate = new javax.swing.JButton();
        jLabel_exercise39Part1 = new javax.swing.JLabel();
        jLabel_result = new javax.swing.JLabel();
        jLabel11_outputA = new javax.swing.JLabel();
        jPanel__exercise64Part1 = new javax.swing.JPanel();
        jLabel_exercis64Part1 = new javax.swing.JLabel();
        jButton_calculate = new javax.swing.JButton();
        jLabel_outputA = new javax.swing.JLabel();
        jLabel_outputB = new javax.swing.JLabel();
        jLabel_sum = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel__exercise14Part2 = new javax.swing.JPanel();
        jLabel_exercise14Part2 = new javax.swing.JLabel();
        jButton__calculate = new javax.swing.JButton();
        jLabel13_outputA = new javax.swing.JLabel();
        jLabel_outputMin = new javax.swing.JLabel();
        jLabel_outputMax = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_outputMatrix = new javax.swing.JTable();
        jTextField_inputWidhtMatrix = new javax.swing.JTextField();
        jTextField_inputHeightMatrix = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel__exercise39Part2 = new javax.swing.JPanel();
        jLabel__exercise39Part2 = new javax.swing.JLabel();
        jButton___calculate = new javax.swing.JButton();
        jLabel_matrix = new javax.swing.JLabel();
        jLabel_outputNumbersOfColumn = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable__outputMatrix = new javax.swing.JTable();
        jTextField__inputWidhtMatrix = new javax.swing.JTextField();
        jTextField__inputHeightMatrix = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel_exercise14Part3 = new javax.swing.JLabel();
        jTextField_inputWidhtMatrixPart3 = new javax.swing.JTextField();
        jButton_calculatePart3 = new javax.swing.JButton();
        jLabel_resultPart3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField_inputHeitMatrixPart3 = new javax.swing.JTextField();
        jLabel_exercise39Part3 = new javax.swing.JLabel();
        jButton_result = new javax.swing.JButton();
        jLabel_Result = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel_exercise64Part3 = new javax.swing.JLabel();
        jTextField1_part4 = new javax.swing.JTextField();
        jButton_resultPart3 = new javax.swing.JButton();
        jTextField2_part3 = new javax.swing.JTextField();
        jTextField3_part3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_exercise39Part4 = new javax.swing.JLabel();
        jLabel_inputlastName = new javax.swing.JLabel();
        jLabel_inputfirstJName = new javax.swing.JLabel();
        jLabel_inputmiddleName = new javax.swing.JLabel();
        jLabel_inputcountDaysWorked = new javax.swing.JLabel();
        jLabel_inputsalaryAmount = new javax.swing.JLabel();
        jTextField_imputlastName = new javax.swing.JTextField();
        jTextField_imputfirstJName = new javax.swing.JTextField();
        jTextField_imputmiddleName = new javax.swing.JTextField();
        jTextField_imputcountDaysWorked = new javax.swing.JTextField();
        jTextField_imputsalaryAmount = new javax.swing.JTextField();
        jButton_resultPart4 = new javax.swing.JButton();
        jButton_calculatePart4 = new javax.swing.JButton();
        jLabel_salaryAmount = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_outputWorker = new javax.swing.JTable();
        jTextField_imputFilePath = new javax.swing.JTextField();
        jLabel_inputFielPath = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton_generateCharsPractice2 = new javax.swing.JButton();
        jTextField_output = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_exercise14Part1.setText("<html>Определить, какие элементы массива А встречаются в массиве В.</html>");

        jLabel2_result.setText("результат:");

        jLabel3_outputA.setText("A:");

        jButton1_calculate.setText("Вычислить");
        jButton1_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_calculate_calculateActionPerformed(evt);
            }
        });

        jLabel4_outputB.setText("B: ");

        javax.swing.GroupLayout jPanel_exercise14Part1Layout = new javax.swing.GroupLayout(jPanel_exercise14Part1);
        jPanel_exercise14Part1.setLayout(jPanel_exercise14Part1Layout);
        jPanel_exercise14Part1Layout.setHorizontalGroup(
            jPanel_exercise14Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_exercise14Part1Layout.createSequentialGroup()
                .addComponent(jLabel_exercise14Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 328, Short.MAX_VALUE))
            .addGroup(jPanel_exercise14Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_exercise14Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1_calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2_result)
                    .addComponent(jLabel4_outputB)
                    .addComponent(jLabel3_outputA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_exercise14Part1Layout.setVerticalGroup(
            jPanel_exercise14Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_exercise14Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise14Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3_outputA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4_outputB)
                .addGap(18, 18, 18)
                .addComponent(jLabel2_result)
                .addGap(18, 18, 18)
                .addComponent(jButton1_calculate)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("14", jPanel_exercise14Part1);

        jButton2_calculate.setText("вычислить");
        jButton2_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_calculate_calculateActionPerformed(evt);
            }
        });

        jLabel_exercise39Part1.setText("<html>Заполнить массив А[1..8] числами, вводимыми с клавиатуры. <br/>Найти сумму элементов с четными индексами.</html>");

        jLabel_result.setText("результат");

        jLabel11_outputA.setText("A:");

        javax.swing.GroupLayout jPanel__exercise39Part1Layout = new javax.swing.GroupLayout(jPanel__exercise39Part1);
        jPanel__exercise39Part1.setLayout(jPanel__exercise39Part1Layout);
        jPanel__exercise39Part1Layout.setHorizontalGroup(
            jPanel__exercise39Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__exercise39Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel__exercise39Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise39Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11_outputA)
                    .addComponent(jLabel_result)
                    .addComponent(jButton2_calculate))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel__exercise39Part1Layout.setVerticalGroup(
            jPanel__exercise39Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__exercise39Part1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel_exercise39Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_result)
                .addGap(18, 18, 18)
                .addComponent(jLabel11_outputA)
                .addGap(18, 18, 18)
                .addComponent(jButton2_calculate)
                .addContainerGap(500, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("39", jPanel__exercise39Part1);

        jLabel_exercis64Part1.setText("<html>Задан одномерный массив A[1..18]. Сформировать новый массив B[1..17],<br/> элементы которого определяются по формуле B[i]=abs(a[i]-a[i+1]). Найти сумму четных элементов массива B. </html>");

        jButton_calculate.setText("Вычислить");
        jButton_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculateActionPerformed(evt);
            }
        });

        jLabel_outputA.setText("A:");

        jLabel_outputB.setText("B:");

        jLabel_sum.setText("сумма:");

        javax.swing.GroupLayout jPanel__exercise64Part1Layout = new javax.swing.GroupLayout(jPanel__exercise64Part1);
        jPanel__exercise64Part1.setLayout(jPanel__exercise64Part1Layout);
        jPanel__exercise64Part1Layout.setHorizontalGroup(
            jPanel__exercise64Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__exercise64Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel__exercise64Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel__exercise64Part1Layout.createSequentialGroup()
                        .addComponent(jButton_calculate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel__exercise64Part1Layout.createSequentialGroup()
                        .addGroup(jPanel__exercise64Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_outputB)
                            .addComponent(jLabel_exercis64Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_outputA)
                            .addComponent(jLabel_sum))
                        .addContainerGap(71, Short.MAX_VALUE))))
        );
        jPanel__exercise64Part1Layout.setVerticalGroup(
            jPanel__exercise64Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__exercise64Part1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_exercis64Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_outputA)
                .addGap(8, 8, 8)
                .addComponent(jLabel_outputB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_sum)
                .addGap(18, 18, 18)
                .addComponent(jButton_calculate)
                .addContainerGap(490, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("64", jPanel__exercise64Part1);

        jTabbedPane1.addTab("Раздел 1", jTabbedPane2);

        jLabel_exercise14Part2.setText("Найти наибольший и наименьший элементы данного двумерного массива. Указать их индексы.");

        jButton__calculate.setText("вычислить");
        jButton__calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton__calculateActionPerformed(evt);
            }
        });

        jLabel13_outputA.setText("A:");

        jLabel_outputMin.setText("min");

        jLabel_outputMax.setText("max");

        jTable_outputMatrix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        jScrollPane2.setViewportView(jTable_outputMatrix);

        jLabel8.setText("Столбцы:");

        jLabel9.setText("Строки:");

        javax.swing.GroupLayout jPanel__exercise14Part2Layout = new javax.swing.GroupLayout(jPanel__exercise14Part2);
        jPanel__exercise14Part2.setLayout(jPanel__exercise14Part2Layout);
        jPanel__exercise14Part2Layout.setHorizontalGroup(
            jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__exercise14Part2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel__exercise14Part2Layout.createSequentialGroup()
                        .addGroup(jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_outputMin)
                            .addComponent(jLabel_outputMax)
                            .addComponent(jLabel_exercise14Part2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel__exercise14Part2Layout.createSequentialGroup()
                        .addComponent(jLabel13_outputA, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel__exercise14Part2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton__calculate)
                                .addContainerGap(349, Short.MAX_VALUE))
                            .addGroup(jPanel__exercise14Part2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_inputWidhtMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_inputHeightMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel__exercise14Part2Layout.setVerticalGroup(
            jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__exercise14Part2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_exercise14Part2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_outputMin)
                .addGap(18, 18, 18)
                .addComponent(jLabel_outputMax)
                .addGap(18, 18, 18)
                .addGroup(jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13_outputA)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel__exercise14Part2Layout.createSequentialGroup()
                        .addGroup(jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_inputWidhtMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel__exercise14Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_inputHeightMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addComponent(jButton__calculate)))
                .addContainerGap(392, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("14", jPanel__exercise14Part2);

        jLabel__exercise39Part2.setText("<html> Вывести на экран матрицу 4x5. Определить номера столбцов, содержащих не более половины положительных<br/> элементов.</html>");

        jButton___calculate.setText("вычислить");
        jButton___calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton___calculateActionPerformed(evt);
            }
        });

        jLabel_matrix.setText("Матрица: ");

        jLabel_outputNumbersOfColumn.setText("номера столбцов: ");

        jTable__outputMatrix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(jTable__outputMatrix);

        jTextField__inputHeightMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField__inputHeightMatrixActionPerformed(evt);
            }
        });

        jLabel6.setText("Строки:");

        jLabel7.setText("Столбцы:");

        javax.swing.GroupLayout jPanel__exercise39Part2Layout = new javax.swing.GroupLayout(jPanel__exercise39Part2);
        jPanel__exercise39Part2.setLayout(jPanel__exercise39Part2Layout);
        jPanel__exercise39Part2Layout.setHorizontalGroup(
            jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__exercise39Part2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel__exercise39Part2Layout.createSequentialGroup()
                        .addComponent(jLabel_matrix)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel__exercise39Part2Layout.createSequentialGroup()
                        .addGroup(jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel__exercise39Part2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_outputNumbersOfColumn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel__exercise39Part2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton___calculate)
                                    .addGroup(jPanel__exercise39Part2Layout.createSequentialGroup()
                                        .addGroup(jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField__inputHeightMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField__inputWidhtMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        jPanel__exercise39Part2Layout.setVerticalGroup(
            jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__exercise39Part2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel__exercise39Part2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_outputNumbersOfColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_matrix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel__exercise39Part2Layout.createSequentialGroup()
                        .addGroup(jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField__inputHeightMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel__exercise39Part2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField__inputWidhtMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jButton___calculate))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("39", jPanel__exercise39Part2);

        jTabbedPane1.addTab("Раздел 2", jTabbedPane3);

        jLabel_exercise14Part3.setText("В заданном слове поменять местами равноотстоящие от концов слова буквы.");

        jTextField_inputWidhtMatrixPart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_inputWidhtMatrixPart3ActionPerformed(evt);
            }
        });

        jButton_calculatePart3.setText("вывести");
        jButton_calculatePart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculatePart3ActionPerformed(evt);
            }
        });

        jLabel_resultPart3.setText("Результат:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise14Part3)
                    .addComponent(jTextField_inputWidhtMatrixPart3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_calculatePart3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_resultPart3))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise14Part3)
                .addGap(30, 30, 30)
                .addComponent(jTextField_inputWidhtMatrixPart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_calculatePart3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_resultPart3)
                .addContainerGap(516, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("14", jPanel6);

        jTextField_inputHeitMatrixPart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_inputHeitMatrixPart3ActionPerformed(evt);
            }
        });

        jLabel_exercise39Part3.setText("Определить длину самой длинной группы цифр во введенной строке.");

        jButton_result.setText("вывести");
        jButton_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resultActionPerformed(evt);
            }
        });

        jLabel_Result.setText("Рeзультат:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise39Part3)
                    .addComponent(jButton_result)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextField_inputHeitMatrixPart3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel_Result)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_exercise39Part3)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_inputHeitMatrixPart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Result))
                .addGap(18, 18, 18)
                .addComponent(jButton_result)
                .addContainerGap(538, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("39", jPanel7);

        jLabel_exercise64Part3.setText("Создать процедуру, которая во введенном слове заменяет один символ другим.");

        jTextField1_part4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_part4ActionPerformed(evt);
            }
        });

        jButton_resultPart3.setText("вывести");
        jButton_resultPart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resultPart3ActionPerformed(evt);
            }
        });

        jTextField2_part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_part3ActionPerformed(evt);
            }
        });

        jTextField3_part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_part3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Результат: ");

        jLabel3.setText("Слово:");

        jLabel4.setText("Буква которую надо заменить:");

        jLabel5.setText("Буква которая заменяется:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise64Part3)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3_part3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(174, 174, 174)
                            .addComponent(jTextField1_part4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jButton_resultPart3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2_part3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel_exercise64Part3)
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_part4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2_part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3_part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_resultPart3)
                    .addComponent(jLabel1))
                .addContainerGap(477, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("64", jPanel8);

        jTabbedPane1.addTab("Раздел 3", jTabbedPane4);

        jLabel2.setText("<html>Создать файл, содержащий значения х (1 x  4, h= 0,5) и значения функции y= cos (x2).  <br/>Вывести на экран данные в виде таблицы и определить, при каком значении х функция принимает <br/>максимальное значение.<html/>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("14", jPanel1);

        jLabel_exercise39Part4.setText("<html>Создать файл, содержащий следующие данные: ФИО рабочего; количество отработанных дней; сумма зарплаты. <br/>Вывести данные из файла на экран. Подсчитать общую сумму зарплаты, выданной рабочим. <br/>Создать новый файл данных, содержащий сведения о рабочих, зарплата которых менее заданного значения.<html/>");

        jLabel_inputlastName.setText("Фамилия");

        jLabel_inputfirstJName.setText("Имя");

        jLabel_inputmiddleName.setText("Отчество");

        jLabel_inputcountDaysWorked.setText("кол-во отработанных днней");

        jLabel_inputsalaryAmount.setText("сумма зарплаты");

        jTextField_imputlastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_imputlastNameActionPerformed(evt);
            }
        });

        jButton_resultPart4.setText("Добавить");
        jButton_resultPart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resultPart4ActionPerformed(evt);
            }
        });

        jButton_calculatePart4.setText("Выполнить");
        jButton_calculatePart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculatePart4ActionPerformed(evt);
            }
        });

        jLabel_salaryAmount.setText("Суммарная зарплата:");

        jTable_outputWorker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Фамилия", "Имя ", "Отчесвто", "Кол-во отработанных  дней", "Сумарная зарплата"
            }
        ));
        jScrollPane4.setViewportView(jTable_outputWorker);

        jTextField_imputFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_imputFilePathActionPerformed(evt);
            }
        });

        jLabel_inputFielPath.setText("Путь файла:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jButton_resultPart4)
                .addGap(127, 127, 127)
                .addComponent(jButton_calculatePart4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise39Part4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel_inputmiddleName)
                            .addGap(117, 117, 117)
                            .addComponent(jTextField_imputmiddleName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_inputfirstJName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_inputlastName))
                            .addGap(117, 117, 117)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_imputfirstJName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(jTextField_imputlastName))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_inputcountDaysWorked)
                            .addComponent(jLabel_inputsalaryAmount)
                            .addComponent(jLabel_salaryAmount)
                            .addComponent(jLabel_inputFielPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_imputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_imputcountDaysWorked, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                .addComponent(jTextField_imputsalaryAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_exercise39Part4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inputlastName)
                    .addComponent(jTextField_imputlastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inputfirstJName)
                    .addComponent(jTextField_imputfirstJName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inputmiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_imputmiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inputcountDaysWorked)
                    .addComponent(jTextField_imputcountDaysWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_inputsalaryAmount)
                    .addComponent(jTextField_imputsalaryAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_imputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inputFielPath))
                .addGap(22, 22, 22)
                .addComponent(jLabel_salaryAmount)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_resultPart4)
                    .addComponent(jButton_calculatePart4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("39", jPanel2);

        jTabbedPane1.addTab("раздел 4", jTabbedPane6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Столбец 1", "Столбец 2", "Столбец 3", "Столбец 4", "Столбец 5", "Столбец 6"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(406, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("tab1", jPanel9);

        jButton_generateCharsPractice2.setText("вывести");
        jButton_generateCharsPractice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_generateCharsPractice2ActionPerformed(evt);
            }
        });

        jTextField_output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_outputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_output, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_generateCharsPractice2))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField_output, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_generateCharsPractice2)
                .addContainerGap(540, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("tab2", jPanel10);

        jTabbedPane1.addTab("таблица", jTabbedPane5);

        jMenu1.setText("File");

        jMenuItem1.setText("выход");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("справка");

        jMenuItem2.setText("Информация");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(jMenu2, "Разработчик: Осминина Ольга");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resultActionPerformed
        String input = jTextField_inputHeitMatrixPart3.getText();
        ArrayList<Integer> sequencesDigits = new ArrayList<Integer>();
        int countDigits = 0;

        // a123
        for (int i = 0; i < input.length(); i++) {
            char inputChar = input.charAt(i); //проходимся по символом 
            int charCode = (int) inputChar; // преобразует символ по таблице
            if (charCode >= 48 & charCode <= 57) { // 48 <= код символа <= 57
                countDigits++;
            } else {
                if (countDigits != 0) {
                    sequencesDigits.add(countDigits);
                }
                if (i != input.length() - 1) {
                    countDigits = 0;
                }
            }
        }
        if (countDigits != 0) {
            sequencesDigits.add(countDigits);
        }

        int maxDigitSequence = Integer.MIN_VALUE;
        for (int i = 0; i < sequencesDigits.size(); i++) {
            if (maxDigitSequence < sequencesDigits.get(i)) {
                maxDigitSequence = sequencesDigits.get(i);
            }
        }

        jLabel_Result.setText("Результат: " + Integer.toString(maxDigitSequence));
    }//GEN-LAST:event_jButton_resultActionPerformed

    private void jButton_calculatePart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculatePart3ActionPerformed
        String input = (jTextField_inputWidhtMatrixPart3.getText()); // задана переменная
        String output = ""; // Переменная для вывода
        int halfLenght = input.length() / 2; // Получаем половину длины
        String leftPart = input.substring(0, halfLenght); // Левая часть строки

        if (input.length() % 2 == 1) { // проверка на четность
            String rightPart = input.substring(halfLenght + 1, input.length()); // Правая часть за исключением среднего элемента
            String middleElement = String.valueOf(input.charAt(halfLenght)); // Средний символ
            String reversedLeftPart = reverseString(leftPart); // Перевернутая левая часть
            String reversedRightPart = reverseString(rightPart); // Перевернутая правая часть

            output += reversedRightPart + middleElement + reversedLeftPart; // Объединяем все в одну строку
        } else {
            String rightPart = input.substring(halfLenght, input.length()); // Правая часть
            String reversedLeftPart = reverseString(leftPart); // Перевернутая левая часть
            String reversedRightPart = reverseString(rightPart); // Перевернутая правая часть

            output += reversedRightPart + reversedLeftPart; // Объединяем все в одну строку
        }

        jLabel_resultPart3.setText(output); // Вывод
    }//GEN-LAST:event_jButton_calculatePart3ActionPerformed

    private void jTextField_inputWidhtMatrixPart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_inputWidhtMatrixPart3ActionPerformed

    }//GEN-LAST:event_jTextField_inputWidhtMatrixPart3ActionPerformed

    private void jTextField_outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_outputActionPerformed

    private void jButton_generateCharsPractice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_generateCharsPractice2ActionPerformed
        String caption = "";
        for (int i = 0; i <= 65535; i++) { // общее количество символов
            char ch; // объявление переменной
            ch = (char) i; // перевод числа в симввол
            caption += String.valueOf(ch); //перевод символа в строку
        }
        jTextField_output.setText(caption);
    }//GEN-LAST:event_jButton_generateCharsPractice2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int[][] twoDimArray = new int[6][6];
        for (int[] a : twoDimArray) {
            for (int i = 0; i < a.length; i++) {
                a[i] = (int) (Math.random() * 100);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField__inputHeightMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField__inputHeightMatrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField__inputHeightMatrixActionPerformed

    private void jButton___calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton___calculateActionPerformed
        int width = Integer.parseInt(jTextField__inputWidhtMatrix.getText()); // считывает число из строки
        int height = Integer.parseInt(jTextField__inputHeightMatrix.getText());

        int[][] twoDimArray = new int[height][width];
        twoDimArray = Generate.generateArray(twoDimArray, - 100, 200);

        ArrayList<Integer> B = new ArrayList<Integer>();
        for (int j = 0; j < twoDimArray.length; j++) {
            int count = 0;
            for (int i = 0; i < width; i++) {
                if (twoDimArray[j][i] > 0) {
                    count++;
                }
            }
            if (count >= 2) {
                B.add(j);
            }

        }

        ShowOnTable.showMatrix(twoDimArray, jTable__outputMatrix);

        jLabel_outputNumbersOfColumn.setText("рузультат: " + Arrays.deepToString(B.toArray()));
    }//GEN-LAST:event_jButton___calculateActionPerformed

    private void jButton__calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton__calculateActionPerformed
        // width -- длина одной строки
        // height -- количество строк
        int width = Integer.parseInt(jTextField_inputWidhtMatrix.getText());
        int height = Integer.parseInt(jTextField_inputHeightMatrix.getText());

        int[][] twoDimArray = new int[height][width];
        twoDimArray = Generate.generateArray(twoDimArray, 0, 100);

        int min = Integer.MAX_VALUE; // минимальное и максимальное значение Integer
        int min_i = -1;
        int min_j = -1;
        for (int i = 0; i < twoDimArray.length; i++) { // сстроки , длина масива
            for (int j = 0; j < twoDimArray[i].length; j++) {
                if (twoDimArray[i][j] < min) {
                    min = twoDimArray[i][j];
                    min_i = i;
                    min_j = j;
                }
            }
        }

        int max = Integer.MIN_VALUE; // максимальное и минимальное занчение Integer
        int max_i = -1; // убедится в правильности алгоритма
        int max_j = -1;
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < width; j++) {
                if (twoDimArray[i][j] > max) {
                    max = twoDimArray[i][j];
                    max_i = i;
                    max_j = j;
                }
            }
        }

        ShowOnTable.showMatrix(twoDimArray, jTable_outputMatrix);

        jLabel_outputMin.setText("min: " + Integer.toString(min) + ", " + Integer.toString(min_i + 1) + ", " + Integer.toString(min_j + 1));
        jLabel_outputMax.setText("max: " + Integer.toString(max) + ", " + Integer.toString(max_i + 1) + ", " + Integer.toString(max_j + 1));
    }//GEN-LAST:event_jButton__calculateActionPerformed

    private void jButton_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculateActionPerformed
        int[] A = new int[18];
        int[] B = new int[17];
        A = Generate.generateArray(A, 0, 100);

        for (int i = 0; i < B.length; i++) {
            B[i] = Math.abs(A[i] - A[i + 1]); // abs- модуль числа
        }
        int sum = 0;
        for (int i = 0; i < B.length; i++) {
            if (i % 2 == 0) { // проверка четности
                sum += B[i];
            }
        }

        String caption = "A: ";
        for (int i : A) {
            caption += Integer.toString(i);
            caption += " ";
        }
        jLabel_outputA.setText(caption);

        caption = "B: ";
        for (int i : B) {
            caption += Integer.toString(i);
            caption += " ";
        }
        jLabel_outputB.setText(caption);
        jLabel_sum.setText("sum: " + Integer.toString(sum));
    }//GEN-LAST:event_jButton_calculateActionPerformed

    private void jButton2_calculate_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_calculate_calculateActionPerformed
        int[] A = new int[10];
        A = Generate.generateArray(A, 0, 100);

        ShowOnLabel.showValue(A, jLabel11_outputA);

        // вывод результатов
        int sum = 0;
        for (int i = 0; i < A.length; i++) {
            if (i % 2 == 0) {
                sum += A[i];
            }
        }
        ShowOnLabel.schowValue(sum, jLabel_result);
    }//GEN-LAST:event_jButton2_calculate_calculateActionPerformed

    private void jButton1_calculate_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_calculate_calculateActionPerformed

        int[] A = new int[10];
        int[] B = new int[10];
        ArrayList<Integer> C = new ArrayList<Integer>(); // массив бесконечной длины
        // вывод рандомных чисел в масив
        A = Generate.generateArray(A, 0, 100);
        B = Generate.generateArray(B, 0, 100);

        //проходим по каждому элементу масивов
        for (int x : A) {
            for (int y : B) {
                if (x == y) {
                    C.add(x);
                }
            }

        }

        jLabel2_result.setText("Результат: " + C.toString());

        String caption = "A: ";
        for (int i : A) {
            caption += Integer.toString(i);
            caption += " ";
        }
        jLabel3_outputA.setText(caption);

        caption = "B: ";
        for (int i : B) {
            caption += Integer.toString(i);
            caption += " ";
        }
        jLabel4_outputB.setText(caption);
    }//GEN-LAST:event_jButton1_calculate_calculateActionPerformed

    private void jTextField_imputlastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_imputlastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_imputlastNameActionPerformed

    private void jButton_resultPart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resultPart4ActionPerformed
        String lastName = jTextField_imputlastName.getText();
        String firstJName = jTextField_imputfirstJName.getText();
        String middleName = jTextField_imputmiddleName.getText();
        int countDaysWorked = Integer.valueOf(jTextField_imputcountDaysWorked.getText());
        int salaryAmount = Integer.valueOf(jTextField_imputsalaryAmount.getText());

        Worker newWorker = new Worker(firstJName, lastName, middleName, countDaysWorked, salaryAmount);

        workers.add(newWorker); //добавляем в масив

        String[][] strWorker = new String[workers.size()][5]; // Ученики записанные в виде строк
        for (int i = 0; i < workers.size(); i++) { // Проходимся по списку учегиков
            Worker get = workers.get(i); // Получение слудющего ученика
            strWorker[i][0] = get.getLastName(); // Записываем фамилию ученика в столбец
            strWorker[i][1] = get.getFirstName(); // Имя в 2 столбец
            strWorker[i][2] = get.getMiddleName(); // Отчество
            strWorker[i][3] = Integer.toString(get.getNumberdaysworked()); // кол-во отработанных дней
            strWorker[i][4] = Integer.toString(get.getSalaryamount()); //сумарная зарплата
        }
        ShowOnTable.showMatrix(strWorker, jTable_outputWorker); // Выводим в таблицу

    }//GEN-LAST:event_jButton_resultPart4ActionPerformed

    private void jButton_calculatePart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculatePart4ActionPerformed
        int summarySallary = 0;
        for (Worker worker : workers) {
            summarySallary = summarySallary + worker.getSalaryamount() * worker.getNumberdaysworked();
        }
        String fileName = jTextField_imputFilePath.getText();
        writeFile(fileName, "Суммарная зарплатаp: " + summarySallary);
       
        jLabel_salaryAmount.setText("Суммарная зарплата: " + Integer.toString(summarySallary));

    }//GEN-LAST:event_jButton_calculatePart4ActionPerformed
    public static String readFile(String fileName) throws FileNotFoundException {
        //Этот спец. объект для построения строки
        StringBuilder sb = new StringBuilder(); // Изменяемая строка
        File file = new File(fileName); // Файл, с которым можно работать

        if (file.exists()) { // Если файл существует, то идем далее
            try {
                // Буфер хранит данные, а буферредер читает из буфера
                BufferedReader in = new BufferedReader(new FileReader(file.getAbsoluteFile()));
                try { // Пытаемся построчно считать файл
                    String s; // Создаем строку, которая будет хранить следующую строку
                    while ((s = in.readLine()) != null) { // Пока есть следующая строка
                        sb.append(s); // Добавляем строку в sb
                        sb.append("\n"); // Добавляем символ переноса строки в sb
                    }
                } finally { // Выполняется в любом случае
                    //Закрыавем файл
                    in.close();
                }
            } catch (IOException e) { // Если произошла ошибка
                throw new RuntimeException(e); // Сообщает о ней
            }
        }

        //Возвращаем полученный текст с файла
        return sb.toString();
    }

    public static void writeFile(String fileName, String text) {
        //Определяем файл
        File file = new File(fileName); // Файл, с которым можно работать

        try {
            //проверяем, что если файл не существует то создаем его
            if (!file.exists()) {
                file.createNewFile();
            }

            //PrintWriter обеспечит возможности записи в файл
            PrintWriter out = new PrintWriter(file.getAbsoluteFile());

            try {
                //Записываем текст у файл
                out.print(text);
            } finally {
                //После чего мы должны закрыть файл
                //Иначе файл не запишется
                out.close();
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
    private void jTextField1_part4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_part4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_part4ActionPerformed

    private void jTextField_inputHeitMatrixPart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_inputHeitMatrixPart3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_inputHeitMatrixPart3ActionPerformed

    private void jButton_resultPart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resultPart3ActionPerformed
        String inputStr = jTextField1_part4.getText();
        String searchStr = jTextField2_part3.getText();
        if (searchStr.length() == 0) {
            jLabel1.setText("Введите символ, который надо заменить");
        }
        String replaceStr = jTextField3_part3.getText();
        if (replaceStr.length() == 0) {
            jLabel1.setText("Введите символ, на которой  надо заменить");
        }
        String output = inputStr.replace(searchStr.charAt(0), replaceStr.charAt(0));
        jLabel1.setText("Результат: " + output);
    }//GEN-LAST:event_jButton_resultPart3ActionPerformed

    private void jTextField2_part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_part3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_part3ActionPerformed

    private void jTextField3_part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_part3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_part3ActionPerformed

    private void jTextField_imputFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_imputFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_imputFilePathActionPerformed

    public static String reverseString(String str) {
        return new StringBuilder(str).reverse().toString(); // Создаем строку, переворачиваем и возращаем
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_calculate;
    private javax.swing.JButton jButton2_calculate;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton___calculate;
    private javax.swing.JButton jButton__calculate;
    private javax.swing.JButton jButton_calculate;
    private javax.swing.JButton jButton_calculatePart3;
    private javax.swing.JButton jButton_calculatePart4;
    private javax.swing.JButton jButton_generateCharsPractice2;
    private javax.swing.JButton jButton_result;
    private javax.swing.JButton jButton_resultPart3;
    private javax.swing.JButton jButton_resultPart4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11_outputA;
    private javax.swing.JLabel jLabel13_outputA;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_result;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_outputA;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_outputB;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Result;
    private javax.swing.JLabel jLabel__exercise39Part2;
    private javax.swing.JLabel jLabel_exercis64Part1;
    private javax.swing.JLabel jLabel_exercise14Part1;
    private javax.swing.JLabel jLabel_exercise14Part2;
    private javax.swing.JLabel jLabel_exercise14Part3;
    private javax.swing.JLabel jLabel_exercise39Part1;
    private javax.swing.JLabel jLabel_exercise39Part3;
    private javax.swing.JLabel jLabel_exercise39Part4;
    private javax.swing.JLabel jLabel_exercise64Part3;
    private javax.swing.JLabel jLabel_inputFielPath;
    private javax.swing.JLabel jLabel_inputcountDaysWorked;
    private javax.swing.JLabel jLabel_inputfirstJName;
    private javax.swing.JLabel jLabel_inputlastName;
    private javax.swing.JLabel jLabel_inputmiddleName;
    private javax.swing.JLabel jLabel_inputsalaryAmount;
    private javax.swing.JLabel jLabel_matrix;
    private javax.swing.JLabel jLabel_outputA;
    private javax.swing.JLabel jLabel_outputB;
    private javax.swing.JLabel jLabel_outputMax;
    private javax.swing.JLabel jLabel_outputMin;
    private javax.swing.JLabel jLabel_outputNumbersOfColumn;
    private javax.swing.JLabel jLabel_result;
    private javax.swing.JLabel jLabel_resultPart3;
    private javax.swing.JLabel jLabel_salaryAmount;
    private javax.swing.JLabel jLabel_sum;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel__exercise14Part2;
    private javax.swing.JPanel jPanel__exercise39Part1;
    private javax.swing.JPanel jPanel__exercise39Part2;
    private javax.swing.JPanel jPanel__exercise64Part1;
    private javax.swing.JPanel jPanel_exercise14Part1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable__outputMatrix;
    private javax.swing.JTable jTable_outputMatrix;
    private javax.swing.JTable jTable_outputWorker;
    private javax.swing.JTextField jTextField1_part4;
    private javax.swing.JTextField jTextField2_part3;
    private javax.swing.JTextField jTextField3_part3;
    private javax.swing.JTextField jTextField__inputHeightMatrix;
    private javax.swing.JTextField jTextField__inputWidhtMatrix;
    private javax.swing.JTextField jTextField_imputFilePath;
    private javax.swing.JTextField jTextField_imputcountDaysWorked;
    private javax.swing.JTextField jTextField_imputfirstJName;
    private javax.swing.JTextField jTextField_imputlastName;
    private javax.swing.JTextField jTextField_imputmiddleName;
    private javax.swing.JTextField jTextField_imputsalaryAmount;
    private javax.swing.JTextField jTextField_inputHeightMatrix;
    private javax.swing.JTextField jTextField_inputHeitMatrixPart3;
    private javax.swing.JTextField jTextField_inputWidhtMatrix;
    private javax.swing.JTextField jTextField_inputWidhtMatrixPart3;
    private javax.swing.JTextField jTextField_output;
    // End of variables declaration//GEN-END:variables
}

class Worker {

    private String firstName; //имя
    private String lastName; //фамилия
    private String middleName; //отчесво
    private int numberdaysworked;
    private int salaryamount;

    public Worker(String firstName, String lastName, String middleName, int numberdaysworked, int salaryamount) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
        this.numberdaysworked = numberdaysworked;
        this.salaryamount = salaryamount;
    }

    public int getNumberdaysworked() {
        return numberdaysworked;
    }

    public int getSalaryamount() {
        return salaryamount;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public void setNumberdaysworked(int numberdaysworked) {
        this.numberdaysworked = numberdaysworked;
    }

    public void setSalaryamount(int salaryamount) {
        this.salaryamount = salaryamount;
    }

}
